site_name: Flutter training
site_author: bayu@biqdev.com
site_url: https://biqdev.com/tutorial/flutter
dev_addr: 0.0.0.0:8080

# https://squidfunk.github.io/mkdocs-material/
theme:
  name: 'material'
  include_sidebar: true
  language: id
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.ico
  logo: assets/images/biq-logo.png
  i18n:
    prev: 'Previous'
    next: 'Next'

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      use_pygments: true
#      linenums: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - 'Welcome': 'index.md'
  - 'CRUD REST API':
    - 'Overview': 'crud-rest-api/overview.md'
    - 'Grid Setup': 'crud-rest-api/grid-setup.md'
    - 'Provider': 'crud-rest-api/provider.md'
    - 'Provider setup': 'crud-rest-api/provider-setup.md'
    - 'Booklist mockup': 'crud-rest-api/booklist-mockup.md'
    - '(C)reate': 'crud-rest-api/create.md'

copyright: "Copyright &copy; 2020 www.biqdev.com;"
